FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow==2.18.0

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow-data/mlflow.db", \
     "--default-artifact-root", "/mlflow-data/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
